### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by leranp** [pilotak/docker-rpi-fan#1]
there is a problem with the script , it doesnt starting the continer

this is the log file
Traceback (most recent call last):
File "/app/fan.py", line 89, in <module>
GPIO.setup(FAN_PIN, GPIO.OUT)
ValueError: Channel must be an integer or list/tuple of integers

this is the compose file
 fan:
    container_name: fan
    restart: unless-stopped
    image: pilotak/rpi-fan
    environment:
      - DESIRED_TEMP=50
      - FAN_PIN=19
      - FAN_PWM_MIN=25
      - FAN_PWM_MAX=100
      - FAN_PWM_FREQ=25
      - P_TEMP=15
      - I_TEMP=0.4
    devices:
      - /dev/gpiomem

**Comment by pilotak** [comment]
It should be fixed, could you please check?

**Comment by leranp** [comment]
looks good, Thanks
